"""Schemas for Phase A Requirement Elicitation."""

from typing import List, Optional, Dict, Any, Union
from pydantic import BaseModel, Field
from generation.ArcGen.schemas.requirements import ArchitectureDriverDimension


class QuestionItem(BaseModel):
    """An architecturally targeted question generated by the elicitation agent."""
    question_id: str = Field(..., description="e.g. 'Q-SCALE-001'")
    target_dimension: ArchitectureDriverDimension = Field(..., description="Target ASR category")
    question_text: str = Field(..., description="The direct question to ask the user")
    why_it_matters: str = Field(..., description="Concise explanation of architectural impact to avoid interrogation fatigue")
    suggested_options: List[str] = Field(default_factory=list, description="Common realistic benchmarks/options")


class ExtractedASR(BaseModel):
    """An architectural driver extracted from user response."""
    dimension: ArchitectureDriverDimension
    raw_text: str
    metric: Optional[str] = None
    value: Optional[Union[str, int, float]] = None
    unit: Optional[str] = None
    confidence: float = 1.0


class ElicitationTurn(BaseModel):
    """A single round in the elicitation interview."""
    turn_number: int
    question: QuestionItem
    user_answer: str
    extracted_asrs: List[ExtractedASR] = Field(default_factory=list)
