@startuml
skinparam componentStyle uml2

title Architecture: ASPERA-3 Processing and Archiving Facility (APAF) (Microservices Architecture)

package "Presentation" {
  [APAFAPIGateway] as COMP-001 <<gateway>>
  [APAFWebApp] as COMP-002 <<module>>
}

package "Application" {
  [AuthNAuthZService] as COMP-003 <<service>>
  [TelemetryAcquisitionService] as COMP-005 <<service>>
  [ProcessingOrchestratorService] as COMP-007 <<service>>
  [TelemetryCleaningService] as COMP-009 <<service>>
  [IDFSProcessingService] as COMP-011 <<service>>
  [CalibrationValidationService] as COMP-013 <<service>>
  [SwRILocalArchiveService] as COMP-015 <<service>>
  [PublicDataDisplayService] as COMP-017 <<service>>
  [ScienceDataAccessService] as COMP-019 <<service>>
}

package "Infrastructure" {
  [AuthNAuthZDB] as COMP-004 <<datastore>>
  [RawTelemetryDB] as COMP-006 <<datastore>>
  [SagaStateDB] as COMP-008 <<datastore>>
  [CleanedTelemetryDB] as COMP-010 <<datastore>>
  [IDFSDataDB] as COMP-012 <<datastore>>
  [CalibrationValidationDB] as COMP-014 <<datastore>>
  [ArchiveMetadataDB] as COMP-016 <<datastore>>
  [PublicDisplayCacheDB] as COMP-018 <<datastore>>
}


COMP-001 --> COMP-003 : HTTPS/REST
COMP-001 --> COMP-002 : HTTPS/REST
COMP-003 --> COMP-004 : PostgreSQL wire protocol
COMP-001 --> COMP-005 : HTTPS/REST
COMP-002 --> COMP-006 : PostgreSQL wire protocol
COMP-001 --> COMP-007 : HTTPS/REST
COMP-002 --> COMP-008 : PostgreSQL wire protocol
COMP-001 --> COMP-009 : HTTPS/REST
COMP-002 --> COMP-010 : PostgreSQL wire protocol
COMP-001 --> COMP-011 : HTTPS/REST
COMP-002 --> COMP-012 : PostgreSQL wire protocol
COMP-001 --> COMP-013 : HTTPS/REST
COMP-013 --> COMP-014 : PostgreSQL wire protocol
COMP-001 --> COMP-015 : HTTPS/REST
COMP-002 --> COMP-016 : PostgreSQL wire protocol
COMP-001 --> COMP-017 : HTTPS/REST
COMP-002 --> COMP-018 : PostgreSQL wire protocol
COMP-001 --> COMP-019 : HTTPS/REST

@enduml